server:
  port: 8999

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/mahadevmane/microservice-configs
